version: '3.8'

services:
  postgresql_14:
    # jdbc:postgresql://localhost:54333/guest?user=guest&password=guest
    container_name: postgresql_14
    ports:
      - "54333:5432"
    image: postgres:14-alpine
    env_file: .env
    healthcheck:
      test: "exit 0"