// Testing getEmployees, which returns a list of employees

### GET employees (limit 10). Successful request
GET http://localhost:8080/employees/

### DELETE all employees. 405 method not allowed.
DELETE http://localhost:8080/employees/

### GET employee by id. Successful request
GET http://localhost:8080/employees/1

### GET employee by id that doesn't exist. 400 bad request.
GET http://localhost:8080/employees/11111

### GET employee by id that is not numeric. 400 bad request.
GET http://localhost:8080/employees/ddd

### DELETE employee by id. Successful request
DELETE http://localhost:8080/employees/999

### POST employee (add). Successful request
POST http://localhost:8080/employees/
Content-Type: application/json

{
  "first_name": "Janina",
  "last_name": "Basoch",
  "department": "Sales",
  "email": "345643398@example.com",
  "date_hired": "2022-04-25"
}

### POST employee by id (update). Successful request.
POST http://localhost:8080/employees/1
Content-Type: application/json

{
  "id":1,
  "first_name":"Tonnie",
  "last_name":"Dallmann",
  "department":"Sales",
  "email":"tdallmann0@studiopress.com",
  "date_hired":"2016-02-23T00:00:00Z"}


### POST employee by id that doesn't exist. 400 bad request.
POST http://localhost:8080/employees/1111111111111
Content-Type: application/json

{}

### POST employee by id that is not numeric. 400 bad request.
POST http://localhost:8080/employees/ddddddd
Content-Type: application/json

{}

### GET employees by department. Successful request.
GET http://localhost:8080/department/support

### GET employees by department that doesn't exist. 400 bad request.
GET http://localhost:8080/department/ddddddd

### DELETE employess by department. 405 method not allowed.
DELETE http://localhost:8080/department/support

### POST employess by department. 405 method not allowed.
POST http://localhost:8080/department/support
