// Testing getEmployees

### GET employees (limit 10). 200 OK
GET http://localhost:8080/employees/

### GET employees (limit 10). 404 Not Found.
GET http://localhost:8080/employes/

### DELETE employees. 405 Method Not Allowed.
DELETE http://localhost:8080/employees/

// Testing getEmployeeById

### GET employee by id. 200 OK
GET http://localhost:8080/employees/1

### GET employee by id that is not numeric. 400 Bad Request.
GET http://localhost:8080/employees/ddd

### GET employee by id that doesn't exist. 404 Not Found.
GET http://localhost:8080/employees/11111

// getEmployeesByDepartment

### GET employees by department. 200 OK
GET http://localhost:8080/department/support

### GET employees by department that doesn't exist. 404 Not Found
GET http://localhost:8080/department/dd

### DELETE employess by department. 405 Method Not Allowed
DELETE http://localhost:8080/department/support

### POST employess by department. 405 Method Not Allowed.
POST http://localhost:8080/department/support

// Testing addEmployee

### POST employee (add). 200 OK
POST http://localhost:8080/employees/
Content-Type: application/json

{
  "first_name": "Amina",
  "last_name": "Ayad",
  "department": "Sales",
  "email": "98374589@example.com",
  "date_hired": "2022-01-25"
}
### Check previous request
GET http://localhost:8080/employees/1001

// Testing updateEmployee

### POST employee by id (update). Successful request.
POST http://localhost:8080/employees/1
Content-Type: application/json

{
  "id":1,
  "first_name":"Tonnie",
  "last_name":"Dallmann",
  "department":"Sales",
  "email":"tdallmann0@studiopress.com",
  "date_hired":"2016-02-23T00:00:00Z"
}
###
GET http://localhost:8080/employees/1

### POST employee by id that is not numeric. 400 bad request.
POST http://localhost:8080/employees/d
Content-Type: application/json

{
  "id": 1,
  "first_name":"Tonnie",
  "last_name":"Dallmann",
  "department":"Sales",
  "email":"tdallmann0@studiopress.com",
  "date_hired":"2016-02-23T00:00:00Z"
}
###

// Testing deleteEmployee

### DELETE employee by id. 200 OK
DELETE http://localhost:8080/employees/999

### Check deleted record. 404 Not Found
GET http://localhost:8080/employees/999

### DELETE the same record. 404 Not Found
DELETE http://localhost:8080/employees/999
